-- Atlas Core V2.1.0
-- Atualizacao idempotente para uma base V2.0.19 existente.
-- Execute este arquivo uma vez no SQL Editor do Supabase.

begin;

-- Permissoes granulares por grupo e coluna.
alter table public.atlas_v2_access_rules
  add column if not exists group_id uuid references public.atlas_v2_groups(id) on delete cascade,
  add column if not exists column_id uuid references public.atlas_v2_columns(id) on delete cascade;

do $$
declare constraint_name text;
begin
  select c.conname into constraint_name
  from pg_constraint c
  where c.conrelid='public.atlas_v2_access_rules'::regclass
    and c.contype='c'
    and pg_get_constraintdef(c.oid) ilike '%num_nonnulls%';
  if constraint_name is not null then
    execute format('alter table public.atlas_v2_access_rules drop constraint %I',constraint_name);
  end if;
end $$;

alter table public.atlas_v2_access_rules
  drop constraint if exists atlas_v2_access_rules_single_scope,
  add constraint atlas_v2_access_rules_single_scope
  check (num_nonnulls(workspace_id,module_id,board_id,group_id,column_id)=1);

create index if not exists atlas_v2_access_rules_group_idx
  on public.atlas_v2_access_rules(user_id,group_id) where group_id is not null;
create index if not exists atlas_v2_access_rules_column_idx
  on public.atlas_v2_access_rules(user_id,column_id) where column_id is not null;
create index if not exists atlas_v2_access_rules_group_fk_idx
  on public.atlas_v2_access_rules(group_id);
create index if not exists atlas_v2_access_rules_column_fk_idx
  on public.atlas_v2_access_rules(column_id);

-- Historico restauravel de registros.
create table if not exists public.atlas_v2_item_history (
  id uuid primary key default gen_random_uuid(),
  board_id uuid not null references public.atlas_v2_boards(id) on delete cascade,
  item_id uuid not null references public.atlas_v2_items(id) on delete cascade,
  column_id uuid references public.atlas_v2_columns(id) on delete set null,
  field_key text not null default '__name__',
  before_value jsonb,
  after_value jsonb,
  action_label text not null default 'Campo atualizado',
  changed_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now()
);

create index if not exists atlas_v2_item_history_item_idx
  on public.atlas_v2_item_history(item_id,created_at desc);
create index if not exists atlas_v2_item_history_board_idx
  on public.atlas_v2_item_history(board_id,created_at desc);

-- Historico dos diagnosticos de armazenamento.
create table if not exists public.atlas_v2_storage_health (
  id bigint generated by default as identity primary key,
  connection_id uuid references public.atlas_v2_storage_connections(id) on delete cascade,
  status text not null check (status in ('healthy','warning','error')),
  latency_ms integer check (latency_ms is null or latency_ms>=0),
  detail text not null default '',
  checked_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now()
);

create index if not exists atlas_v2_storage_health_connection_idx
  on public.atlas_v2_storage_health(connection_id,created_at desc);

-- Controle de execucao unica das automacoes agendadas.
create table if not exists public.atlas_v2_automation_schedule_runs (
  automation_id uuid not null references public.atlas_v2_automations(id) on delete cascade,
  slot_key text not null,
  executed_at timestamptz not null default now(),
  primary key (automation_id,slot_key)
);

alter table public.atlas_v2_item_history enable row level security;
alter table public.atlas_v2_storage_health enable row level security;
alter table public.atlas_v2_automation_schedule_runs enable row level security;

-- Resolve o quadro de um grupo ou coluna sem depender das politicas RLS.
create or replace function public.atlas_v2_can_group(target_group uuid, capability text)
returns boolean
language plpgsql
stable
security definer
set search_path=public,pg_temp
as $$
declare target_board uuid; level_value text;
begin
  if auth.uid() is null or not public.atlas_v2_is_active_user() then return false; end if;
  if public.atlas_v2_is_admin() then return true; end if;
  select board_id into target_board from public.atlas_v2_groups where id=target_group;
  if target_board is null then return false; end if;
  select nivel into level_value
  from public.atlas_v2_access_rules
  where user_id=auth.uid() and group_id=target_group
  order by updated_at desc limit 1;
  if level_value is not null then
    return public.atlas_v2_access_level_allows(level_value,capability);
  end if;
  return public.atlas_v2_can_board(target_board,capability);
end;
$$;

create or replace function public.atlas_v2_can_column(target_column uuid, capability text)
returns boolean
language plpgsql
stable
security definer
set search_path=public,pg_temp
as $$
declare target_board uuid; level_value text;
begin
  if auth.uid() is null or not public.atlas_v2_is_active_user() then return false; end if;
  if public.atlas_v2_is_admin() then return true; end if;
  select board_id into target_board from public.atlas_v2_columns where id=target_column and ativo;
  if target_board is null then return false; end if;
  select nivel into level_value
  from public.atlas_v2_access_rules
  where user_id=auth.uid() and column_id=target_column
  order by updated_at desc limit 1;
  if level_value is not null then
    return public.atlas_v2_access_level_allows(level_value,capability);
  end if;
  return public.atlas_v2_can_board(target_board,capability);
end;
$$;

-- O motor V2.1 reconhece agendas e comparacoes numericas.
create or replace function public.atlas_v2_trigger_matches(
  trigger_data jsonb,event_name text,event_payload jsonb
)
returns boolean
language plpgsql
immutable
set search_path=public,pg_temp
as $$
declare trigger_type text:=coalesce(trigger_data->>'type','item_created');
begin
  if event_name='manual' then return true; end if;
  if trigger_type='item_created' then return event_name='item_created'; end if;
  if trigger_type='field_changed' then
    return event_name='field_changed'
      and coalesce(trigger_data->>'columnId','')=coalesce(event_payload->>'columnId','')
      and (
        coalesce(trigger_data->>'value','')=''
        or lower(trigger_data->>'value')=
          lower(public.atlas_v2_json_scalar(event_payload->'newValue'))
      );
  end if;
  if trigger_type='group_changed' then
    return event_name='group_changed'
      and (
        coalesce(trigger_data->>'groupId','')=''
        or trigger_data->>'groupId'=event_payload->>'newGroupId'
      );
  end if;
  if trigger_type='scheduled' then return event_name='scheduled'; end if;
  return trigger_type='date_reached' and event_name='date_reached';
end;
$$;

create or replace function public.atlas_v2_condition_matches(
  item_context jsonb,condition_data jsonb
)
returns boolean
language plpgsql
immutable
set search_path=public,pg_temp
as $$
declare
  key text:=coalesce(condition_data->>'columnId','');
  op text:=coalesce(condition_data->>'operator','equals');
  actual text;
  expected text:=public.atlas_v2_json_scalar(condition_data->'value');
  numeric_pattern constant text:='^[-+]?[0-9]+([.,][0-9]+)?$';
begin
  actual:=case
    when key='__name__' then coalesce(item_context->>'name','')
    when key='__group__' then coalesce(item_context->>'groupId','')
    else public.atlas_v2_json_scalar(item_context->'values'->key)
  end;
  return case op
    when 'equals' then actual=expected
    when 'not_equals' then actual<>expected
    when 'contains' then position(lower(expected) in lower(actual))>0
    when 'not_contains' then position(lower(expected) in lower(actual))=0
    when 'is_empty' then btrim(actual)=''
    when 'not_empty' then btrim(actual)<>''
    when 'greater_than' then
      actual~numeric_pattern and expected~numeric_pattern
      and replace(actual,',','.')::numeric>replace(expected,',','.')::numeric
    when 'less_than' then
      actual~numeric_pattern and expected~numeric_pattern
      and replace(actual,',','.')::numeric<replace(expected,',','.')::numeric
    else false
  end;
end;
$$;

-- A escrita atomica de valores passa a respeitar grupo e coluna.
create or replace function public.atlas_v2_apply_item_value_change(
  target_item uuid,target_column uuid,target_value jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare target_board uuid; target_group uuid; previous_value jsonb; stored_value jsonb;
  automation_result jsonb; final_context jsonb; children jsonb:='[]'::jsonb;
begin
  if auth.uid() is null then raise exception 'Sessao obrigatoria.' using errcode='42501'; end if;
  select board_id,group_id into target_board,target_group
  from public.atlas_v2_items where id=target_item and not arquivado;
  if target_board is null
     or not public.atlas_v2_can_group(target_group,'edit')
     or not public.atlas_v2_can_column(target_column,'edit') then
    raise exception 'Sem permissao para editar este campo.' using errcode='42501';
  end if;
  if not exists(
    select 1 from public.atlas_v2_columns
    where id=target_column and board_id=target_board and ativo
  ) then
    raise exception 'O campo informado nao pertence ao quadro.';
  end if;
  select valor into previous_value
  from public.atlas_v2_item_values
  where item_id=target_item and column_id=target_column;
  if target_value is null or target_value='null'::jsonb or
     (jsonb_typeof(target_value)='string' and btrim(public.atlas_v2_json_scalar(target_value))='') then
    delete from public.atlas_v2_item_values
    where item_id=target_item and column_id=target_column;
    stored_value:=null;
  else
    insert into public.atlas_v2_item_values(item_id,column_id,valor,updated_by)
    values(target_item,target_column,target_value,auth.uid())
    on conflict(item_id,column_id) do update
      set valor=excluded.valor,updated_by=excluded.updated_by,updated_at=now();
    stored_value:=target_value;
  end if;
  if previous_value is distinct from stored_value then
    automation_result:=public.atlas_v2_run_automations(
      target_board,target_item,'field_changed',
      jsonb_build_object(
        'columnId',target_column::text,
        'oldValue',previous_value,
        'newValue',stored_value
      )
    );
  else
    automation_result:=jsonb_build_object(
      'success',true,'executed',0,'skipped',0,'failed',0
    );
  end if;
  final_context:=public.atlas_v2_item_context(target_item);
  select coalesce(
    jsonb_agg(public.atlas_v2_item_context(id) order by ordem,id),
    '[]'::jsonb
  ) into children
  from public.atlas_v2_items
  where parent_item_id=target_item and not arquivado;
  return jsonb_build_object(
    'success',coalesce((automation_result->>'success')::boolean,true),
    'changed',previous_value is distinct from stored_value,
    'automation_result',automation_result,
    'item_context',final_context,
    'children',children
  );
end;
$$;

create or replace function public.atlas_v2_register_attachment(
  p_item_id uuid,p_column_id uuid,p_storage_connection_id uuid,p_file_id text,p_folder_id text,
  p_nome text,p_mime_type text,p_tamanho bigint,p_view_url text,p_thumbnail_url text,p_ordem integer
)
returns setof public.atlas_v2_attachments
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare target_board uuid; target_group uuid;
begin
  if auth.uid() is null then raise exception 'Sessao obrigatoria.' using errcode='42501'; end if;
  select board_id,group_id into target_board,target_group
  from public.atlas_v2_items where id=p_item_id and not arquivado;
  if target_board is null
     or not public.atlas_v2_can_group(target_group,'edit')
     or not public.atlas_v2_can_column(p_column_id,'edit') then
    raise exception 'Sem permissao para anexar arquivos.' using errcode='42501';
  end if;
  return query
  insert into public.atlas_v2_attachments(
    item_id,column_id,storage_connection_id,file_id,folder_id,nome,mime_type,tamanho,
    view_url,thumbnail_url,ordem,criado_por
  ) values(
    p_item_id,p_column_id,p_storage_connection_id,p_file_id,coalesce(p_folder_id,''),
    coalesce(nullif(btrim(p_nome),''),'Arquivo'),
    coalesce(p_mime_type,'application/octet-stream'),coalesce(p_tamanho,0),
    coalesce(p_view_url,''),coalesce(p_thumbnail_url,''),
    coalesce(p_ordem,0),auth.uid()
  ) returning *;
end;
$$;

-- Processamento remoto das agendas. O primeiro usuario ativo que consultar o
-- Atlas depois do horario dispara o lote, e a chave impede execucao duplicada.
create or replace function public.atlas_v2_process_scheduled_automations()
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare a public.atlas_v2_automations%rowtype; target_item uuid;
  frequency_value text; time_value time; slot_value text;
  inserted integer; processed integer:=0; failed integer:=0;
  local_now timestamp:=timezone('America/Sao_Paulo',now());
begin
  if auth.uid() is null or not public.atlas_v2_is_active_user() then
    raise exception 'Usuario sem acesso ativo.' using errcode='42501';
  end if;
  for a in
    select * from public.atlas_v2_automations
    where ativo and gatilho->>'type'='scheduled'
      and public.atlas_v2_can_board(board_id,'edit')
    order by created_at,id
  loop
    begin
      frequency_value:=coalesce(nullif(a.gatilho->>'frequency',''),'daily');
      time_value:=coalesce(nullif(a.gatilho->>'time','')::time,'08:00'::time);
      if frequency_value<>'hourly' and local_now::time<time_value then continue; end if;
      slot_value:=case frequency_value
        when 'hourly' then to_char(local_now,'YYYY-MM-DD-HH24')
        when 'weekly' then to_char(local_now,'IYYY-IW')
        else to_char(local_now,'YYYY-MM-DD')
      end;
      insert into public.atlas_v2_automation_schedule_runs(automation_id,slot_key)
      values(a.id,slot_value) on conflict do nothing;
      get diagnostics inserted=row_count;
      if inserted=0 then continue; end if;
      for target_item in
        select id from public.atlas_v2_items
        where board_id=a.board_id and not arquivado
        order by ordem,id
      loop
        perform public.atlas_v2_run_automations(
          a.board_id,target_item,'scheduled',
          jsonb_build_object('slot',slot_value,'checkedAt',now()),a.id
        );
        processed:=processed+1;
      end loop;
    exception when others then
      failed:=failed+1;
    end;
  end loop;
  return jsonb_build_object(
    'success',failed=0,
    'processed',processed,
    'failed',failed,
    'checked_at',now()
  );
end;
$$;

-- Politicas refinadas.
drop policy if exists atlas_v2_groups_select on public.atlas_v2_groups;
drop policy if exists atlas_v2_groups_write on public.atlas_v2_groups;
drop policy if exists atlas_v2_groups_insert on public.atlas_v2_groups;
drop policy if exists atlas_v2_groups_update on public.atlas_v2_groups;
drop policy if exists atlas_v2_groups_delete on public.atlas_v2_groups;
create policy atlas_v2_groups_select on public.atlas_v2_groups
  for select to authenticated using(public.atlas_v2_can_group(id,'view'));
create policy atlas_v2_groups_insert on public.atlas_v2_groups
  for insert to authenticated
  with check(public.atlas_v2_can_board(board_id,'configure'));
create policy atlas_v2_groups_update on public.atlas_v2_groups
  for update to authenticated
  using(public.atlas_v2_can_board(board_id,'configure'))
  with check(public.atlas_v2_can_board(board_id,'configure'));
create policy atlas_v2_groups_delete on public.atlas_v2_groups
  for delete to authenticated
  using(public.atlas_v2_can_board(board_id,'configure'));

drop policy if exists atlas_v2_columns_select on public.atlas_v2_columns;
drop policy if exists atlas_v2_columns_write on public.atlas_v2_columns;
drop policy if exists atlas_v2_columns_insert on public.atlas_v2_columns;
drop policy if exists atlas_v2_columns_update on public.atlas_v2_columns;
drop policy if exists atlas_v2_columns_delete on public.atlas_v2_columns;
create policy atlas_v2_columns_select on public.atlas_v2_columns
  for select to authenticated using(public.atlas_v2_can_column(id,'view'));
create policy atlas_v2_columns_insert on public.atlas_v2_columns
  for insert to authenticated
  with check(public.atlas_v2_can_board(board_id,'configure'));
create policy atlas_v2_columns_update on public.atlas_v2_columns
  for update to authenticated
  using(public.atlas_v2_can_board(board_id,'configure'))
  with check(public.atlas_v2_can_board(board_id,'configure'));
create policy atlas_v2_columns_delete on public.atlas_v2_columns
  for delete to authenticated
  using(public.atlas_v2_can_board(board_id,'configure'));

drop policy if exists atlas_v2_items_select on public.atlas_v2_items;
drop policy if exists atlas_v2_items_insert on public.atlas_v2_items;
drop policy if exists atlas_v2_items_update on public.atlas_v2_items;
drop policy if exists atlas_v2_items_delete on public.atlas_v2_items;
create policy atlas_v2_items_select on public.atlas_v2_items
  for select to authenticated using(public.atlas_v2_can_group(group_id,'view'));
create policy atlas_v2_items_insert on public.atlas_v2_items
  for insert to authenticated with check(public.atlas_v2_can_group(group_id,'create'));
create policy atlas_v2_items_update on public.atlas_v2_items
  for update to authenticated
  using(public.atlas_v2_can_group(group_id,'edit'))
  with check(public.atlas_v2_can_group(group_id,'edit'));
create policy atlas_v2_items_delete on public.atlas_v2_items
  for delete to authenticated using(public.atlas_v2_can_group(group_id,'delete'));

drop policy if exists atlas_v2_item_values_select on public.atlas_v2_item_values;
drop policy if exists atlas_v2_item_values_write on public.atlas_v2_item_values;
drop policy if exists atlas_v2_item_values_insert on public.atlas_v2_item_values;
drop policy if exists atlas_v2_item_values_update on public.atlas_v2_item_values;
drop policy if exists atlas_v2_item_values_delete on public.atlas_v2_item_values;
create policy atlas_v2_item_values_select on public.atlas_v2_item_values
  for select to authenticated using(
    public.atlas_v2_can_column(column_id,'view')
    and exists(
      select 1 from public.atlas_v2_items i
      where i.id=item_id and public.atlas_v2_can_group(i.group_id,'view')
    )
  );
create policy atlas_v2_item_values_insert on public.atlas_v2_item_values
  for insert to authenticated with check(
    public.atlas_v2_can_column(column_id,'edit')
    and exists(
      select 1 from public.atlas_v2_items i
      where i.id=item_id and public.atlas_v2_can_group(i.group_id,'edit')
    )
  );
create policy atlas_v2_item_values_update on public.atlas_v2_item_values
  for update to authenticated
  using(
    public.atlas_v2_can_column(column_id,'edit')
    and exists(
      select 1 from public.atlas_v2_items i
      where i.id=item_id and public.atlas_v2_can_group(i.group_id,'edit')
    )
  )
  with check(
    public.atlas_v2_can_column(column_id,'edit')
    and exists(
      select 1 from public.atlas_v2_items i
      where i.id=item_id and public.atlas_v2_can_group(i.group_id,'edit')
    )
  );
create policy atlas_v2_item_values_delete on public.atlas_v2_item_values
  for delete to authenticated using(
    public.atlas_v2_can_column(column_id,'edit')
    and exists(
      select 1 from public.atlas_v2_items i
      where i.id=item_id and public.atlas_v2_can_group(i.group_id,'edit')
    )
  );

drop policy if exists atlas_v2_attachments_select on public.atlas_v2_attachments;
drop policy if exists atlas_v2_attachments_write on public.atlas_v2_attachments;
drop policy if exists atlas_v2_attachments_insert on public.atlas_v2_attachments;
drop policy if exists atlas_v2_attachments_update on public.atlas_v2_attachments;
drop policy if exists atlas_v2_attachments_delete on public.atlas_v2_attachments;
create policy atlas_v2_attachments_select on public.atlas_v2_attachments
  for select to authenticated using(
    public.atlas_v2_can_column(column_id,'view')
    and exists(
      select 1 from public.atlas_v2_items i
      where i.id=item_id and public.atlas_v2_can_group(i.group_id,'view')
    )
  );
create policy atlas_v2_attachments_insert on public.atlas_v2_attachments
  for insert to authenticated with check(
    public.atlas_v2_can_column(column_id,'edit')
    and exists(
      select 1 from public.atlas_v2_items i
      where i.id=item_id and public.atlas_v2_can_group(i.group_id,'edit')
    )
  );
create policy atlas_v2_attachments_update on public.atlas_v2_attachments
  for update to authenticated
  using(
    public.atlas_v2_can_column(column_id,'edit')
    and exists(
      select 1 from public.atlas_v2_items i
      where i.id=item_id and public.atlas_v2_can_group(i.group_id,'edit')
    )
  )
  with check(
    public.atlas_v2_can_column(column_id,'edit')
    and exists(
      select 1 from public.atlas_v2_items i
      where i.id=item_id and public.atlas_v2_can_group(i.group_id,'edit')
    )
  );
create policy atlas_v2_attachments_delete on public.atlas_v2_attachments
  for delete to authenticated using(
    public.atlas_v2_can_column(column_id,'edit')
    and exists(
      select 1 from public.atlas_v2_items i
      where i.id=item_id and public.atlas_v2_can_group(i.group_id,'edit')
    )
  );

drop policy if exists atlas_v2_item_history_select on public.atlas_v2_item_history;
drop policy if exists atlas_v2_item_history_insert on public.atlas_v2_item_history;
create policy atlas_v2_item_history_select on public.atlas_v2_item_history
  for select to authenticated using(
    public.atlas_v2_can_board(board_id,'view')
    and (column_id is null or public.atlas_v2_can_column(column_id,'view'))
  );
create policy atlas_v2_item_history_insert on public.atlas_v2_item_history
  for insert to authenticated with check(
    changed_by=auth.uid()
    and public.atlas_v2_can_board(board_id,'edit')
    and (column_id is null or public.atlas_v2_can_column(column_id,'edit'))
  );

drop policy if exists atlas_v2_storage_health_admin on public.atlas_v2_storage_health;
create policy atlas_v2_storage_health_admin on public.atlas_v2_storage_health
  for all to authenticated
  using(public.atlas_v2_is_admin())
  with check(public.atlas_v2_is_admin());

drop policy if exists atlas_v2_automation_schedule_runs_manage on public.atlas_v2_automation_schedule_runs;
create policy atlas_v2_automation_schedule_runs_manage on public.atlas_v2_automation_schedule_runs
  for all to authenticated
  using(public.atlas_v2_is_admin())
  with check(public.atlas_v2_is_admin());

-- Funcoes SECURITY DEFINER ficam disponiveis apenas para usuarios autenticados.
revoke all on function public.atlas_v2_can_group(uuid,text) from public,anon;
revoke all on function public.atlas_v2_can_column(uuid,text) from public,anon;
revoke all on function public.atlas_v2_apply_item_value_change(uuid,uuid,jsonb) from public,anon;
revoke all on function public.atlas_v2_register_attachment(uuid,uuid,uuid,text,text,text,text,bigint,text,text,integer) from public,anon;
revoke all on function public.atlas_v2_process_scheduled_automations() from public,anon;
grant execute on function public.atlas_v2_can_group(uuid,text) to authenticated;
grant execute on function public.atlas_v2_can_column(uuid,text) to authenticated;
grant execute on function public.atlas_v2_apply_item_value_change(uuid,uuid,jsonb) to authenticated;
grant execute on function public.atlas_v2_register_attachment(uuid,uuid,uuid,text,text,text,text,bigint,text,text,integer) to authenticated;
grant execute on function public.atlas_v2_process_scheduled_automations() to authenticated;
grant select,insert on table public.atlas_v2_item_history to authenticated;
grant select,insert on table public.atlas_v2_storage_health to authenticated;
grant usage,select on sequence public.atlas_v2_storage_health_id_seq to authenticated;

notify pgrst,'reload schema';

commit;
